variables:
  $ANONYMIZED_PASSWORD: 'Password123'
  $ANONYMIZED_PHONE: '1234 5678'
  $ANONYMIZED_FAX: '1234 5678'
  $ANONYMIZED_MAIL: '@trash-mail.com'
  $ANONYMIZED_STREET: ' test avenue'
  $ANONYMIZED_IP: '0.0.0.0'
config:
  # table_name:
  #    - [$colName, $concatString, $concatFieldName, $additionalString, $encrypt(bool), $concatFieldNameAfter(bool)]
  customer_entity:
    - [ 'firstname', 'firstname_', 'entity_id', '', false, true ]
    - [ 'lastname','lastname_', 'entity_id', '', false, true ]
    - [ 'email', 'dev_', 'entity_id', '$ANONYMIZED_MAIL', false, true ]
    - [ 'password_hash', '$ANONYMIZED_PASSWORD', null, null, true, true ]
  customer_address_entity:
    - [ 'firstname', 'firstname_', 'entity_id', '', false, true ]
    - [ 'lastname', 'lastname_', 'entity_id', '', false, true ]
    - [ 'street', '$ANONYMIZED_STREET', 'entity_id', '', false, false ]
    - [ 'city', 'city_', 'entity_id', '', false, true ]
    - [ 'telephone', '$ANONYMIZED_PHONE', 'entity_id', '', false, true ]
    - [ 'fax', '$ANONYMIZED_FAX', 'entity_id', '', false, true ]
  customer_grid_flat:
    - [ 'name', 'name_', 'entity_id', '', false, true ]
    - [ 'email', 'dev_', 'entity_id', '$ANONYMIZED_MAIL', false, true ]
    - [ 'shipping_full', 'shipping_full_', 'entity_id', '', false, true ]
    - [ 'billing_full', 'billing_full_', 'entity_id', '', false, true ]
    - [ 'billing_firstname', 'billing_firstname_', 'entity_id', '', false, true ]
    - [ 'billing_lastname', 'billing_lastname_', 'entity_id', '', false, true ]
    - [ 'billing_telephone', '$ANONYMIZED_PHONE', 'entity_id', '', false, true ]
    - [ 'billing_street', '$ANONYMIZED_STREET', 'entity_id', '', false, false ]
    - [ 'billing_city', 'billing_city_', 'entity_id', '', false, true ]
    - [ 'billing_company', 'billing_company_', 'entity_id', '', false, true ]
  email_contact:
    - [ 'email', 'dev_', 'email_contact_id', '$ANONYMIZED_MAIL', false, true ]
  newsletter_subscriber:
    - [ 'subscriber_email', 'dev_', 'subscriber_id', '$ANONYMIZED_MAIL', false, true ]
  quote:
    - [ 'customer_email', 'dev_', 'entity_id', '$ANONYMIZED_MAIL', false, true ]
    - [ 'customer_firstname', 'customer_firstname_', 'entity_id', '', false, true ]
    - [ 'customer_lastname', 'customer_lastname_', 'entity_id', '', false, true ]
    - [ 'remote_ip', '$ANONYMIZE_IP', null, null, false, true ]
  quote_address:
    - [ 'email', 'dev_', 'address_id', '$ANONYMIZED_MAIL', false, true ]
    - [ 'firstname', 'firstname_', 'address_id', '', false, true ]
    - [ 'lastname', 'lastname_', 'address_id', '', false, true ]
    - [ 'company', 'company_', 'address_id', '', false, true ]
    - [ 'street', '$ANONYMIZED_STREET', 'address_id', '', false, false ]
    - [ 'city', 'city_', 'address_id', '', false, true ]
    - [ 'telephone', '$ANONYMIZED_PHONE', 'address_id', '', false, true ]
    - [ 'fax', '$ANONYMIZED_FAX', 'address_id', '', false, true ]
  sales_creditmemo_grid:
    - [ 'billing_name', 'billing_name_', 'entity_id', '', false, true ]
    - [ 'billing_address', 'billing_address_', 'entity_id', '', false, true ]
    - [ 'shipping_address', 'shipping_address_', 'entity_id', '', false, true ]
    - [ 'customer_name', 'customer_name_', 'entity_id', '', false, true ]
    - [ 'customer_email', 'dev_', 'entity_id', '$ANONYMIZED_MAIL', false, true ]
  sales_invoice_grid:
    - [ 'billing_name', 'billing_name_', 'entity_id', '', false, true ]
    - [ 'billing_address', 'billing_address_', 'entity_id', '', false, true ]
    - [ 'shipping_address', 'shipping_address_', 'entity_id', '', false, true ]
    - [ 'customer_name', 'customer_name_', 'entity_id', '', false, true ]
    - [ 'customer_email', 'dev_', 'entity_id', '$ANONYMIZED_MAIL', false, true ]
  sales_order:
    - [ 'customer_email', 'dev_', 'entity_id', '$ANONYMIZED_MAIL', false, true ]
    - [ 'customer_firstname', 'customer_firstname_', 'entity_id', '', false, true ]
    - [ 'customer_lastname', 'customer_lastname_', 'entity_id', '', false, true ]
  sales_order_address:
    - [ 'lastname', 'lastname_', 'entity_id', '', false, true ]
    - [ 'firstname', 'firstname_', 'entity_id', '', false, true ]
    - [ 'street', '$ANONYMIZED_STREET', 'entity_id', '', false, false ]
    - [ 'city', 'city_', 'entity_id', '', false, true ]
    - [ 'email', 'dev_', 'entity_id', '$ANONYMIZED_MAIL', false, true ]
    - [ 'telephone', '$ANONYMIZED_PHONE', 'entity_id', '', false, true ]
    - [ 'company', 'company_', 'entity_id', '', false, true ]
  sales_order_grid:
    - [ 'billing_name', 'billing_name_', 'entity_id', '', false, true ]
    - [ 'shipping_name', 'shipping_name_', 'entity_id', '', false, true ]
    - [ 'billing_address', 'billing_address_', 'entity_id', '', false, true ]
    - [ 'shipping_address', 'shipping_address_', 'entity_id', '', false, true ]
    - [ 'customer_name', 'customer_name_', 'entity_id', '', false, true ]
    - [ 'customer_email', 'dev_', 'entity_id', '$ANONYMIZED_MAIL', false, true ]
  sales_shipment_grid:
    - [ 'billing_name', 'billing_name_', 'entity_id', '', false, true ]
    - [ 'shipping_name', 'shipping_name_', 'entity_id', '', false, true ]
    - [ 'billing_address', 'billing_address_', 'entity_id', '', false, true ]
    - [ 'shipping_address', 'shipping_address_', 'entity_id', '', false, true ]
    - [ 'customer_name', 'customer_name_', 'entity_id', '', false, true ]
    - [ 'customer_email', 'dev_', 'entity_id', '$ANONYMIZED_MAIL', false, true ]
sql_query: # applying DB SQL queries
  #  alias_name: 'UPDATE table SET column=....'
  clean_quote: 'DELETE FROM quote'
  sales_order_gift: 'UPDATE sales_order SET gift_info = NULL'
  truncate_admin_notice: "TRUNCATE adminnotification_inbox"
  truncate_reporting_users: "TRUNCATE reporting_users;"
magerun2_run:
  #  alias_name: '[command]'
  cache_clean: 'cache:clean'
