config:
  default:
    0:
      web/unsecure/base_url: 'http://site.net/'
      web/secure/base_url: 'https://site.net/'
  websites:
    2:
     web/unsecure/base_url: 'http://ca.site.net/'
     web/secure/base_url: 'https://ca.site.net/'
     web/unsecure/base_link_url: 'http://ca.site.net/'
    3:
     web/unsecure/base_url: 'http://uk.site.net/'
     web/secure/base_url: 'https://uk.site.net/'
  stores:
    0:
      web/secure/base_url:
        delete: true
      web/unsecure/base_url:
        delete: true
