<?php
declare(strict_types=1);

namespace Montikids\MagentoCliUtil\Model\Magento;

use Montikids\MagentoCliUtil\Enum\Magento\EnvFileInterface;
use Montikids\MagentoCliUtil\Exception\InvalidConfigException;

/**
 * Works with store config values encrypted by Magento
 */
class ValueEncryptor
{
    /**
     * Latest algorithm hash version that Magento uses for encryption
     * @link https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Encryption/Encryptor.php
     * @var int
     */
    private const HASH_VERSION = 3;

    /**
     * @var int
     */
    private const NONCE_LENGTH = SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_NPUBBYTES;

    /**
     * Prefix of base64-encoded crypt keys generated by Magento 2.4.7+
     * @see \Magento\Framework\Config\ConfigOptionsListConstants::STORE_KEY_ENCODED_RANDOM_STRING_PREFIX
     * @var string
     */
    private const ENCODED_KEY_PREFIX = 'base64';

    /**
     * @var string[]|null
     */
    private $cachedKeys;

    /**
     * @var EnvFileReader
     */
    private $envFileReader;

    /**
     * Initialize dependencies
     */
    public function __construct()
    {
        $this->envFileReader = new EnvFileReader();
    }

    /**
     * @param string $value
     * @return string
     * @throws \SodiumException
     * @throws InvalidConfigException
     */
    public function encrypt(string $value): string
    {
        $cryptKey = $this->decodeKey($this->getLatestCryptKey());
        $cryptKeyVersion = $this->getCryptKeyCurrentVersion();

        $nonce = random_bytes(self::NONCE_LENGTH);
        $encryptedValue = sodium_crypto_aead_chacha20poly1305_ietf_encrypt($value, $nonce, $nonce, $cryptKey);
        $base64EncodedValue = base64_encode("{$nonce}{$encryptedValue}");

        $result = sprintf(
            '%s:%s:%s',
            $cryptKeyVersion,
            self::HASH_VERSION,
            $base64EncodedValue
        );

        return $result;
    }

    /**
     * Returns the raw key bytes, the same way Magento does
     * @see \Magento\Framework\Encryption\Encryptor::decodeKey()
     *
     * @param string $key
     * @return string
     */
    private function decodeKey(string $key): string
    {
        $isEncoded = (0 === strpos($key, self::ENCODED_KEY_PREFIX));
        $result = $isEncoded ? (string)base64_decode(substr($key, strlen(self::ENCODED_KEY_PREFIX))) : $key;

        return $result;
    }

    /**
     * Returns the latest crypt key from the Magento env file (@see EnvFileInterface::FILE_PATH)
     *
     * @return string
     * @throws InvalidConfigException
     */
    public function getLatestCryptKey(): string
    {
        $allKeys = $this->getCryptKeys();
        $currentVersion = $this->getCryptKeyCurrentVersion();
        $result = $allKeys[$currentVersion];

        return $result;
    }

    /**
     * @return int
     * @throws InvalidConfigException
     */
    private function getCryptKeyCurrentVersion(): int
    {
        $allKeys = $this->getCryptKeys();
        $result = count($allKeys) - 1;

        return $result;
    }

    /**
     * Returns all Magento crypt keys (there is more than one, if crypt key was re-generated) stored in the env file
     * (@see EnvFileInterface::FILE_PATH)
     *
     * @return string[]
     * @throws InvalidConfigException
     */
    private function getCryptKeys(): array
    {
        if (null === $this->cachedKeys) {
            $keysStr = (string)$this->envFileReader->readStringValue(EnvFileInterface::PATH_CRYPT_KEY);

            if ('' === $keysStr) {
                $error = sprintf(
                    "Can't read the crypt key ('%s'). Please, check your config file: %s",
                    EnvFileInterface::PATH_CRYPT_KEY,
                    EnvFileInterface::FILE_PATH
                );

                throw new InvalidConfigException($error);
            }

            $this->cachedKeys = preg_split('/\s+/s', $keysStr);
        }

        return $this->cachedKeys;
    }
}
